### PR TITLE
index: Use Math.E over numeric constant

### PR DESCRIPTION
**Pull request by kevinji**
Due to the precision of JavaScript's doubles, the two numbers are equivalent.

### CODE REVIEW

**Comment by kgryte** [comment]
@mc10 Thanks for the PR; however, we're not interested in reassignment. Hard coding the number ensures that the constant is the coded value. Otherwise, someone could hijack global state (e.g., create a new `Math` object having a constant value which is no longer correct). One purpose of this package is to explicitly avoid globals.

**Comment by kevinji** [comment]
That doesn't make sense... if you're importing this as a node module, all files in all modules are run in their own scope, so `Math` couldn't possibly be overridden unless *you* add some code in this specific file that does that (which would be quite pointless). Since `Math` constants are available in every modern implementation of JavaScript, I see no reason why you are hardcoding in duplicate numeric values.

**Comment by kgryte** [comment]
In browser environments, you are still accessing the same global state.

**Comment by kgryte** [comment]
Furthermore, yes, modules have their own scope, but they still access shared global state, otherwise global variables would not work in Node. See [here](https://github.com/nodejs/node/blob/f6247a945ca8c41ba8738883d948282f36b9671c/lib/module.js#L569).

Next, reassignment makes opaque the constant value (i.e., you have to look elsewhere for the actual value). These implementations choose to be explicit.

**Comment by kevinji** [comment]
> In browser environments, you are still accessing the same global state.

This is a node module, so I fail to see how that's relevant.

> Furthermore, yes, modules have their own scope, but they still access shared global state, otherwise global variables would not work in Node.

Yes, there is the global standard library, but even within a module, as long as you are using `require` or `import` to include your files, each file still runs with a fresh global state. (Also, again, this isn't even relevant unless you have some code within this module that modifies `Math`.)

> Next, reassignment makes opaque the constant value (i.e., you have to look elsewhere for the actual value). These implementations choose to be explicit.

I fail to see how "3.14..." (which isn't even pi; it's just an approximation) is more explicit than `Math.PI`. For one, it's possible for your numeric constant to have a digit wrong, but `Math.PI`, which has been standardized in the spec, will not suffer from that issue.

Since it seems like we're not going to come to an agreement, I don't see any point of continuing this conversation, but honestly these modules are more pointless than [left-pad](https://github.com/stevemao/left-pad), since you are duplicating functionality in the global namespace at the cost of efficiency and space for absolutely no benefit.

**Comment by kgryte** [comment]
Browser environments: browserify, webpack. The target environment is not only Node.

And no, you are incorrect. The proof is simple enough. In one file,

``` javascript
// foo.js
module.exports = Math.PI;
```
In another file,
``` javascript
global.Math = {
  'PI': 3.14
};
var PI = require( './foo.js' );

console.log( PI );
```
What is the value of `PI`? According to you, the value is the specification defined value. But it is not. Global state is shared. As I pointed out, read the `node` source and see how V8 `vm` instances are created.

Re: being explicit. The issue is not whether the value is the same. The issue is, if I read the source, how many steps do I need to take to know what the exported value is. By using reassignment, I cannot simply read the module source and know the value. Instead, I have to read the source and then perform another out-of-band search to know what `Math.PI`, for example, is according to the specification.

Re: standardization. You seem to hold the belief that the standard is infallible. This is a false assumption, especially when it comes to the math library. See [here](https://github.com/stdlib-js/stdlib/blob/develop/docs/native_math_bugs.md).

Re: agreement. Don't use the packages. We created them for a particular purpose. They were and are meaningful to us and they have achieved the aim we wanted. End of story.

Criticizing us and calling the packages "meaningless" without knowing the context in which they were created and without knowing why does nothing to advance the conversation. You have particular opinions and so do we. Respect that we might have valid justifications, even if they are not shared by you.

**Pull request closed without merging**
